### ISSUE TITLE
Implementation for Pico-8

### ISSUE THREAD

**Issue by bennyschudel** [timm/lua#2]
Hi Tim

I tried to port this random generator to "[Pico-8](https://www.lexaloffle.com/pico-8.php)" but because of it's limited number space I was unsure on how to calculate the multiplier and the modulus to get a good result.

a = 16807.0
b = 32749.0 -- nearest prime to max of 32767

the results were quite predictable.
By adding a fraction of ".1234" to the modulus the results improved quite a bit.

a = 16807.0
b = 32749.1234

Do you see a better way to calculate the variables or is it maybe just fine with my try and error approach?
Many thanks!

Ben

**Comment by timm** [comment]
so sorry i've only just seen this

i don't have any insight into this random number generator.   so sorry!
